### ISSUE TITLE
Negotation about style

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [TNTU-RS-internship/scalhive-theme#16]
@hal-hive, @vitalyte пропоную наступний стиль сторінок.

В хедері сайту, а саме в пунктах навігації розмістити шрифт Igra Sans (оскільки він професійний, сучасний і одночасно підкреслює дружелюбність та не потребує жирного стилю). А також використовувати Igra Sans в тексті кнопок, футера та посилань. 

Загальний текст опису розділів змінити на Montserrat, він краще вписується в сайт та має різні ступені жирності.

А шрифт заголовку поточної сторінки (в хедері) можна залишити той, що був або новий (Inter), який показано на зображеннях знизу. Також пропоную внести зміни до стилістики гугл форми, а саме розмістити її в новий блок, що забезпечить вільну зміну фону сторінки і це не конфліктуватиме з кольором тексту форми.

Скетч сторінки контактів:
![Image](https://github.com/TNTU-RS-internship/scalhive-theme/assets/61250339/8d4f013c-a321-46c6-9890-8f126dd28fd1)

Скетч сторінки "Про нас"
![Image](https://github.com/TNTU-RS-internship/scalhive-theme/assets/61250339/855fc69c-705b-4ad8-8fad-6d089c1a616d)

**Comment by hal-hive** [comment]
@Nazarii-Melnyk @vitalyte 
1. По шрифтах підтримую, ці виглядають краще. 
2. Стиль сторінки контактів - підтримую, тільки зображення поверніть, виглядає, що воно не тим боком.
3. Поточний фон сторінок занадто темний.
4. Банерне зображення ми також в майбутньому замінимо. Це занадто темне. Треба глянути що є по scalhive з попередніх версій сайту.

**Comment by Nazarii-Melnyk** [comment]
> 1. По шрифтах підтримую, ці виглядають краще.
> 2. Стиль сторінки контактів - підтримую, тільки зображення поверніть, виглядає, що воно не тим боком.
> 3. Поточний фон сторінок занадто темний.
> 4. Банерне зображення ми також в майбутньому замінимо. Це занадто темне. Треба глянути що є по scalhive з попередніх версій сайту.

Зрозуміло, дякуємо.

Єдине щодо цього зображення то насправді так і планувалось, що воно буде таким чином перевернуте.
@misha1301, як думаєш, наскільки воно буде гірше виглядати, якщо його перевернути горизонтально і підправити розміри під форму?

**Comment by misha1301** [comment]
> @Nazarii-Melnyk @vitalyte
> 
> 1. По шрифтах підтримую, ці виглядають краще.
> 2. Стиль сторінки контактів - підтримую, тільки зображення поверніть, виглядає, що воно не тим боком.
> 3. Поточний фон сторінок занадто темний.
> 4. Банерне зображення ми також в майбутньому замінимо. Це занадто темне. Треба глянути що є по scalhive з попередніх версій сайту.

До речі, щодо контактної фото то я її перевернув у бік форми, яку необхідно заповнити. Це більше керуюче зображення, яке вказує напрям фокусу користувача. 
Але в загальному це просто фото для прикладу, яке можна буде замінити.

Дякую, за фітбек)

**Comment by vitalyte** [comment]
@Nazarii-Melnyk 
текст для сторінки about us
**ScalHive: Pioneering Software Solutions Since 2015**

Founded in Ukraine, ScalHive has rapidly established itself as a beacon of innovation in software development. We are a vibrant team of young, forward-thinking professionals, including PhDs, MScs, and BScs, dedicated to pushing the boundaries of technology.

**Customized Excellence in Software Development**

Our forte lies in crafting tailor-made software solutions that align precisely with your unique business challenges. With our profound expertise in creating advanced web-based applications, we transform your vision into reality. Trust ScalHive to guide your project from conception to completion with precision and flair.

**Data Engineering Expertise for Every Business Scale**

We empower businesses of all sizes by scaling their data engineering capabilities with top-tier talent. Our distinctive offshore staffing model, combined with a hands-on approach, guarantees the perfect match of expertise for your projects – efficiently, affordably, and within your timelines.

**A Comprehensive, Client-Focused Approach**

Our process begins with a deep understanding of your specific requirements. We then meticulously source, recruit, and integrate the ideal data engineers into your team. But our support doesn’t stop there – we ensure continuous management and assistance to keep your team productive, cohesive, and perfectly attuned to your business objectives.

**Data: The Heartbeat of Digital Success**

At ScalHive, we're not just passionate about software; we believe in the power of data as the cornerstone of digital success. Our commitment is to equip you with exceptional data engineering talent, enabling you to construct a world-class team. Together, let's harness the potential of data to propel your business towards its goals.
